#! /usr/bin/env python3
"""
Script to plot on fault variables.
"""

import xarray as xr
import matplotlib.pyplot as plt
import numpy as np
import os, glob, re, imageio
from pdf2image import convert_from_path
from user_defined_params import *

#
SMALL_SIZE = 10
r = 10e6 # half range to show stresses in Pa.

# Read in file name from terminal.
# fname = input("Enter the file name : ")

def plot_roughness(fname):
  a = xr.open_dataset(fname)
  #print (a)

  b1 = a.peak
  b2 = a.pypx
  b3 = a.pypz

  fig1 = plt.figure(figsize=(12,6))
  plt.rc('font', size=SMALL_SIZE)

  ax11 = fig1.add_subplot(2,2,1)
  b1.plot()
  ax11.set_xlabel('')
  #ax11.set_ylabel('')
  ax11.set_aspect('equal',adjustable='box')

  ax12 = fig1.add_subplot(2,2,2)
  b2.plot()
  ax12.set_xlabel('')
  ax12.set_ylabel('')
  ax11.set_aspect('equal',adjustable='box')
  
  ax21 = fig1.add_subplot(2,2,3)
  b3.plot()
  #ax21.set_ylabel('')
  ax11.set_aspect('equal',adjustable='box')
  
  plt.savefig(fname + ".png", dpi = 600)
  plt.close()

  return (fig1,)

def tryint(s):
    try:
        return int(s)
    except:
        return s

def alphanum_key(s):
    return [tryint(c) for c in re.split('([0-9]+)', s)]

def sort_nicely(l):
    l.sort(key=alphanum_key, reverse=False)
    return l

def generate_gif():
  #images = []
  #dirFiles = []
  #for fname in os.listdir(os.getcwd()):
  #  name, file_extension = os.path.splitext(fname)
  #  if '.png' in file_extension:
  #    dirFiles += fname
  #print(dirFiles)
  #for fname in sorted(dirFiles):
  #  print(fname)
  #  images.append(imageio.imread(fname))
  #imageio.mimsave('on_fault_vars.gif',images)
  filenames = glob.glob('.//*.png')
  filenames = sort_nicely(filenames)
  with imageio.get_writer('./on_fault_vars.gif', mode='I') as writer:
      for filename in filenames:
          image = imageio.v2.imread(filename)
          #img = convert_from_path(filename)[0]
          #image = np.array(img.getdata(), np.uint8).reshape(img.size[1], img.size[0], 3)
          writer.append_data(image)

def seek_numbers_filename(x):
    return (x[6:10])

#dirFiles = os.listdir(os.getcwd())
def _main_func(description):
    plot_roughness('roughness.nc')

if __name__ == "__main__":
    _main_func(__doc__)

#print(*dirFiles)
#sorted_file_list = sorted(dirFiles, key=seek_numbers_filename)
#print(sorted_file_list)

#fig = plt.figure()
#anim = animation.FuncAnimation(fig, plot_fault, frames = 1, interval = 1, blit=False)


