#! /usr/bin/env python3
"""
Script to connect eqquasi and sord.
"""
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np
import os
from user_defined_params import *

def connect(src, dst):
    coor_in = xr.open_dataset(str(src) + ".coor.nc")
    ien_in = xr.open_dataset(str(src) + ".ien.nc")
    nsmp_in = xr.open_dataset(str(src) + ".nsmp.nc")
    numnp = len(coor_in.coordinates)
    nx = (xmax - xmin)/dx + 1
    nz = (zmax - zmin)/dx + 1
    ny = numnp/(nx*nz)
    print(numnp,nx,ny,nz)

def _main_func(description):
    src = str("mesh")
    dst = str("sord")
    connect(src, dst)

if __name__ == "__main__":
    _main_func(__doc__)
