#! /usr/bin/env python3
"""
Script to plot temporal evolutions of on-fault variables
    on a vertical and a horizontal profiles.
"""

import xarray as xr
import matplotlib.pyplot as plt
import numpy as np
import os, glob, re, imageio, sys
from pdf2image import convert_from_path
from user_defined_params import par
from lib import *

ninterval = 20 # plot results in every 20 steps.

def generate_timeseries_profile_all(model_path, mode, var, ninterval,nwindow):
    # extract time series information from all the model folders,
    # and return them in the array data.
    filenames = glob.glob(model_path+'/fault.?????.nc')
    filenames = sort_nicely(filenames)
    num_files = len(filenames)

    # fault.r.nc must exist
    # extract dimension information from restart file.
    a =xr.open_dataset(model_path+'/fault.r.nc')
    shear_strike = a.shear_strike
    num_rows = shear_strike.shape[0]
    num_cols = shear_strike.shape[1]
    middle_row_index = num_rows // 4 # 1/4th quartile depth of the whole model depth
    middle_col_index = num_cols // 2
    middle_row_index = middle_row_index*3

    print(num_files, num_rows, num_cols, middle_row_index, middle_col_index)

    if mode==1:
        # plot vertical profile, count rows
        data = np.zeros((num_rows, num_files))
        data_ave = np.zeros((num_rows-nwindow+1, num_files))
    elif mode ==2:
        # plot horizontal profile, count columns
        data = np.zeros((num_cols, num_files))
        data_ave = np.zeros((num_cols-nwindow+1, num_files))
    
    itag = 0
    for file1 in filenames:
        b = xr.open_dataset(file1)
        if var    =='effective_normal':
            res   = b.effective_normal
            res   = res/1.e6
            ylabel='Stress MPa'
            
        elif var  =='slip_rate':
            res   = b.slip_rate
            ylabel='Slip rate m/s'
            
        elif var  =='shear_strike':
            res   = b.shear_strike
            res   = res/1.e6
            ylabel='Stress MPa'
            
        elif var  =='slips':
            res   = b.slips
            ylabel='Slip along strike m'
            
        itag = itag + 1
        if mode == 1:
            data[:,itag-1] = res[:, middle_col_index]
        elif mode == 2:
            for i in range(num_cols):
                data[i,itag-1] = res[middle_row_index,i]
        
        data_ave[:,itag-1] = boxcar_average(data[:,itag-1],nwindow) 
        
        data0 = data_ave[:,::ninterval]
    return data0 # [# of nodes, # of steps]

#dirFiles = os.listdir(os.getcwd())
def _main_func(description):
    
    if len(sys.argv)==2 or len(sys.argv)==4:

        if sys.argv[1] == '-h':
            print('plotAccumulated plots accumulated slips on a horizontal/vertical profile')
            print('Usage: plotAccumulated [mode:1=Vert/2=Hori] [# of cycles: integer] [nwindow]')
        else:
        
            mode = int(sys.argv[1]) # mode from terminal input
            ncyc = int(sys.argv[2]) # # of cycles from terminal input
            nwindow = int(sys.argv[3]) # # of fault nodes for the averaing window
            
            if mode == 1:
                xlabel = 'Along Dip on-fault Nodes'
                ylabel = 'Slip Along Dip m'
                out_file = 'cVerticalProfile.slips.png'
                title  = 'Accumulated Slips on a Vertical Profile'
                print('Generating accumulated slips on a vertical profile')
            elif mode == 2:
                xlabel = 'Along Strike on-fault Nodes'
                ylabel = 'Slip Along Strike m'
                out_file = 'cHorizontalProfile.slips.png'
                title  = 'Accumulated Slips on a Horizontal Profile'
                print('Generating accumulated slips on a Horizontal profile')
                
            for i in range(ncyc):
                model_path = 'Q'+str(i) 
                print('Processing the '+str(i)+'th cycle')
                tmp = generate_timeseries_profile_all(model_path, mode, 'slips', ninterval,nwindow)
                #print(tmp.shape)
                if i == 0:
                    data = tmp
                else:
                    # adding final slip from last batch to the new data - tmp.
                    result = tmp + data[:, -1, np.newaxis] 
                    data = np.concatenate((data, result), axis=1)
                
            num_cols = data.shape[1]
            print('Plot every ',ninterval,' steps')
            print('Time time steps are', num_cols)
            
            plt.figure()
            for i in range(num_cols):
                plt.plot(data[:,i],color='black', linewidth=1)
                
            plt.xlabel(xlabel)
            plt.ylabel(ylabel)
            plt.title(title)
            plt.savefig(out_file, dpi=300)
    else:
        print('Missing arguments. Type plotProfilesAll -h')
    
if __name__ == "__main__":
    _main_func(__doc__)


